<h1>Irakasleak</h1>
<table border=1>
    <tr>
        <th>Izena</th>
        <th>Abizena</th>
    </tr>
    <tr>
        <td>jose</td>
        <td>Garcia</td>
    </tr>
    <tr>
        <td>luisa</td>
        <td>Gonzales</td>
    </tr>
    <tr>
        <td>nagore</td>
        <td>Eguzkiagirre</td>
    </tr>
    <tr>
        <td>xabier</td>
        <td>Villanueva</td>
    </tr>
    <tr>
        <td>hector</td>
        <td>Garcia</td>
    </tr>
    <tr>
        <td>dilan</td>
        <td>Velazquez</td>
    </tr>
    <tr>
        <td>alice</td>
        <td>Martinez</td>
    </tr>
    <tr>
        <td>naroa</td>
        <td>Razquin</td>
    </tr>
    <tr>
        <td>asier</td>
        <td>Martin</td>
    </tr>
    <tr>
        <td>julen</td>
        <td>Cano</td>
    </tr>
</table>
